
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.hluther.parser;

/** CUP generated class containing symbol constants. */
public class CanvasSym {
  /* terminals */
  public static final int GREEN = 10;
  public static final int SQUARE = 16;
  public static final int CANVAS = 13;
  public static final int PNG = 22;
  public static final int DIMENSIONY = 18;
  public static final int NAME = 19;
  public static final int DIMENSIONX = 17;
  public static final int BLUE = 9;
  public static final int LITERAL = 7;
  public static final int COLON = 4;
  public static final int RED = 8;
  public static final int ID = 6;
  public static final int HEX = 11;
  public static final int TYPE = 20;
  public static final int COMMA = 5;
  public static final int CURLYBRACKETO = 2;
  public static final int EOF = 0;
  public static final int GIF = 21;
  public static final int error = 1;
  public static final int CURLYBRACKETC = 3;
  public static final int HEXCODE = 12;
  public static final int INTEGER = 23;
  public static final int SIZE = 15;
  public static final int BACKGROUND = 14;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "CURLYBRACKETO",
  "CURLYBRACKETC",
  "COLON",
  "COMMA",
  "ID",
  "LITERAL",
  "RED",
  "BLUE",
  "GREEN",
  "HEX",
  "HEXCODE",
  "CANVAS",
  "BACKGROUND",
  "SIZE",
  "SQUARE",
  "DIMENSIONX",
  "DIMENSIONY",
  "NAME",
  "TYPE",
  "GIF",
  "PNG",
  "INTEGER"
  };
}

