
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.hluther.parser;

/** CUP generated class containing symbol constants. */
public class ColorsSym {
  /* terminals */
  public static final int GREEN = 9;
  public static final int CURLYBRACKETC = 3;
  public static final int INTEGER = 13;
  public static final int COLON = 4;
  public static final int EOF = 0;
  public static final int HEXCODE = 11;
  public static final int CURLYBRACKETO = 2;
  public static final int ID = 6;
  public static final int error = 1;
  public static final int COMMA = 5;
  public static final int COLORS = 12;
  public static final int BLUE = 8;
  public static final int HEX = 10;
  public static final int RED = 7;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "CURLYBRACKETO",
  "CURLYBRACKETC",
  "COLON",
  "COMMA",
  "ID",
  "RED",
  "BLUE",
  "GREEN",
  "HEX",
  "HEXCODE",
  "COLORS",
  "INTEGER"
  };
}

