
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.hluther.parser;

/** CUP generated class containing symbol constants. */
public class PaintSym {
  /* terminals */
  public static final int LESSEQUALSTHAN = 31;
  public static final int SQUAREBRACKETO = 15;
  public static final int MOREEQUALSTHAN = 32;
  public static final int EQUALS = 8;
  public static final int IDLITERAL = 7;
  public static final int INSTRUCTIONS = 18;
  public static final int VARS = 17;
  public static final int SQUAREBRACKETC = 16;
  public static final int INTEGER = 36;
  public static final int BETWEEN = 35;
  public static final int PARENTHESISO = 19;
  public static final int INT = 3;
  public static final int MINUS = 12;
  public static final int SEMICOLON = 9;
  public static final int AND = 26;
  public static final int PARENTHESISC = 20;
  public static final int LESSTHAN = 34;
  public static final int OR = 27;
  public static final int COMMA = 10;
  public static final int CURLYBRACKETO = 24;
  public static final int PLUS = 11;
  public static final int IF = 29;
  public static final int ID = 2;
  public static final int EOF = 0;
  public static final int BOOLEAN = 5;
  public static final int CURLYBRACKETC = 25;
  public static final int TRUE = 37;
  public static final int error = 1;
  public static final int ELSE = 30;
  public static final int WHILE = 23;
  public static final int MORETHAN = 33;
  public static final int FULLSTOP = 21;
  public static final int COMPARATION = 28;
  public static final int STRING = 4;
  public static final int STRINGLITERAL = 6;
  public static final int FALSE = 38;
  public static final int DIVISION = 14;
  public static final int MULTIPLICATION = 13;
  public static final int PAINT = 22;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ID",
  "INT",
  "STRING",
  "BOOLEAN",
  "STRINGLITERAL",
  "IDLITERAL",
  "EQUALS",
  "SEMICOLON",
  "COMMA",
  "PLUS",
  "MINUS",
  "MULTIPLICATION",
  "DIVISION",
  "SQUAREBRACKETO",
  "SQUAREBRACKETC",
  "VARS",
  "INSTRUCTIONS",
  "PARENTHESISO",
  "PARENTHESISC",
  "FULLSTOP",
  "PAINT",
  "WHILE",
  "CURLYBRACKETO",
  "CURLYBRACKETC",
  "AND",
  "OR",
  "COMPARATION",
  "IF",
  "ELSE",
  "LESSEQUALSTHAN",
  "MOREEQUALSTHAN",
  "MORETHAN",
  "LESSTHAN",
  "BETWEEN",
  "INTEGER",
  "TRUE",
  "FALSE"
  };
}

