
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.hluther.parser;

/** CUP generated class containing symbol constants. */
public class TimeSym {
  /* terminals */
  public static final int CURLYBRACKETC = 3;
  public static final int INTEGER = 16;
  public static final int TIME = 9;
  public static final int LITERAL = 12;
  public static final int COLON = 6;
  public static final int SQUAREBRACKETC = 5;
  public static final int CANVASID = 8;
  public static final int DURATION = 15;
  public static final int EOF = 0;
  public static final int CURLYBRACKETO = 2;
  public static final int ID = 14;
  public static final int IMAGES = 13;
  public static final int STARTID = 10;
  public static final int error = 1;
  public static final int COMMA = 7;
  public static final int SQUAREBRACKETO = 4;
  public static final int END = 11;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "CURLYBRACKETO",
  "CURLYBRACKETC",
  "SQUAREBRACKETO",
  "SQUAREBRACKETC",
  "COLON",
  "COMMA",
  "CANVASID",
  "TIME",
  "STARTID",
  "END",
  "LITERAL",
  "IMAGES",
  "ID",
  "DURATION",
  "INTEGER"
  };
}

